version: '3.4'

services:
  oar.apps.webspa.mockapi:
    image: oar.apps.webspa.mockapi
    build:
      context: .
      dockerfile: Dockerfile.connexion
    environment:
      NODE_ENV: development
    ports:
      - 8080
      - 9228:8080
    tty: true