version: "3.4"

services:
  oar.apps.webspa.mockapi:
    image: oar.apps.webspa.mockapi
    build:
      context: .
      dockerfile: Dockerfile.connexion
    env_file:
        - ./.env
    environment:
      NODE_ENV: development
    ports:
      - 8080
      - 9328:8080
    tty: true
  oar.apps.webspa:
    image: oar.apps.webspa
    depends_on:
      - oar.apps.webspa.mockapi
    build:
      context: .
      dockerfile: Dockerfile
      args:
        REACT_APP_ENV_VAR: ${REACT_APP_ENV_VAR}
        REACT_APP_API_HOST: ${REACT_APP_API_HOST}
        REACT_APP_API_PORT: ${REACT_APP_API_PORT}
    environment:
      NODE_ENV: development   
    ports:
      - 80
      - 9329:80
    tty: true
