/**
 * OpenAccessOnContainers Catalogstore
 * This is a sample server Catalogstore server. For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: huseyindenizkivrak@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Contributer } from './Contributer';
import { Language } from './Language';
import { Publisher } from './Publisher';
import { Type } from './Type';

export interface Catalog { 
    contributer?: Array<Contributer>;
    coverage?: string;
    creator?: Contributer;
    date?: string;
    description?: string;
    format?: string;
    id?: string;
    identifier?: Array<string>;
    language?: Language;
    publisher?: Publisher;
    relation?: Array<string>;
    right?: string;
    source?: string;
    subject?: Array<string>;
    title?: string;
    type?: Array<Type>;
}