/**
 * OpenAccessOnContainers Catalogstore
 * This is a sample server Catalogstore server. For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: huseyindenizkivrak@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Publisher { 
    id?: string;
    name?: string;
}